import { db } from '@appdeploy/sdk';

export const DAY_KEYS=['mon','tue','wed','thu','fri','sat','sun'] as const;
export type DayKey=typeof DAY_KEYS[number];
export type DayHours={enabled:boolean;open:string;close:string};
export type BusinessHours={timezone:'Africa/Johannesburg';days:Record<DayKey,DayHours>;updatedAt:number};
const BASE:Record<DayKey,DayHours>={mon:{enabled:true,open:'09:00',close:'17:00'},tue:{enabled:true,open:'09:00',close:'17:00'},wed:{enabled:true,open:'09:00',close:'17:00'},thu:{enabled:true,open:'09:00',close:'17:00'},fri:{enabled:true,open:'09:00',close:'17:00'},sat:{enabled:true,open:'09:00',close:'15:00'},sun:{enabled:false,open:'09:00',close:'15:00'}};
function copyDays():Record<DayKey,DayHours>{return{mon:{...BASE.mon},tue:{...BASE.tue},wed:{...BASE.wed},thu:{...BASE.thu},fri:{...BASE.fri},sat:{...BASE.sat},sun:{...BASE.sun}}}
function validTime(v:unknown){return /^([01]\d|2[0-3]):[0-5]\d$/.test(String(v??''))}
function cleanTime(v:unknown,fallback:string){return validTime(v)?String(v):fallback}
function minuteOf(v:string){const[h,m]=v.split(':').map(Number);return h*60+m}
function normalise(input:Record<string,unknown>):BusinessHours{const defaults=copyDays(),rawDays=(input.days&&typeof input.days==='object'?input.days:{}) as Record<string,unknown>,days=copyDays();for(const key of DAY_KEYS){const raw=(rawDays[key]&&typeof rawDays[key]==='object'?rawDays[key]:{}) as Record<string,unknown>;days[key]={enabled:raw.enabled===undefined?defaults[key].enabled:Boolean(raw.enabled),open:cleanTime(raw.open,defaults[key].open),close:cleanTime(raw.close,defaults[key].close)}}return{timezone:'Africa/Johannesburg',days,updatedAt:Number(input.updatedAt)||0}}
export function defaultBusinessHours():BusinessHours{return{timezone:'Africa/Johannesburg',days:copyDays(),updatedAt:0}}
export async function getBusinessHours(businessId:string){const row=(await db.list<Record<string,unknown>>(`business-hours:${businessId}`,{limit:1})).items[0];if(!row)return defaultBusinessHours();return{id:row.id,...normalise(row)}}
export async function saveBusinessHours(businessId:string,input:Record<string,unknown>){const next=normalise({days:input.days,updatedAt:Date.now()});if(!DAY_KEYS.some(key=>next.days[key].enabled))throw new Error('Keep at least one working day open, or turn online booking off instead.');for(const key of DAY_KEYS){const day=next.days[key];if(day.enabled&&minuteOf(day.close)<=minuteOf(day.open))throw new Error('Closing time must be later than opening time on every open day.')}const existing=(await db.list<Record<string,unknown>>(`business-hours:${businessId}`,{limit:1})).items[0];if(existing){const[ok]=await db.update(`business-hours:${businessId}`,[{id:existing.id,record:next}]);if(!ok)throw new Error('Working hours could not be saved');return{id:existing.id,...next}}const[id]=await db.add(`business-hours:${businessId}`,[next]);if(!id)throw new Error('Working hours could not be saved');return{id,...next}}
const DAY_BY_INDEX:DayKey[]=['sun','mon','tue','wed','thu','fri','sat'];
export function slotTimesForDate(hours:BusinessHours,date:string,duration:number,slotInterval=30){const key=DAY_BY_INDEX[new Date(`${date}T12:00:00Z`).getUTCDay()],day=hours.days?.[key]||BASE[key];if(!day?.enabled)return[];const start=minuteOf(day.open),close=minuteOf(day.close),serviceMinutes=Math.max(15,Math.min(480,Number(duration)||60)),step=Math.max(15,Math.min(120,Number(slotInterval)||30)),slots:string[]=[];for(let t=start;t+serviceMinutes<=close;t+=step)slots.push(`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`);return slots}
