import { db, notifications, storage } from '@appdeploy/sdk';
import { listTeam } from './entitlements';
import { registerPartition } from './launch-readiness';

export type CommunicationSettings = { bookingConfirmation: boolean; reminder24h: boolean; morningReminder: boolean; reminder2h: boolean; reviewRequest: boolean; rebookReminder: boolean; noShowRecovery: boolean; waitlistRecovery: boolean; ownerPush: boolean; customerChannel: 'whatsapp_manual' | 'provider' };
export type BookingPolicy = { depositRequired: boolean; depositType: 'fixed' | 'percentage'; depositValue: number; cancellationHours: number; noShowPolicyText: string; collectionProvider: 'none' | 'provider' };
export type CommunicationStatus = 'scheduled' | 'ready' | 'handed_off' | 'sent' | 'cancelled' | 'skipped';
export type CommunicationRecord = { businessId: string; customerId?: string; appointmentId?: string; waitlistId?: string; waitlistPartition?: string; customerName: string; customerPhone: string; kind: 'booking_confirmation' | 'reminder_24h' | 'reminder_morning' | 'reminder_2h' | 'review_request' | 'rebook_reminder' | 'no_show_recovery' | 'booking_cancelled' | 'waitlist_opening'; channel: 'whatsapp_manual' | 'provider'; status: CommunicationStatus; message: string; dueAt: number; createdAt: number; updatedAt: number; handedOffAt?: number; automation: boolean };
export type WaitlistEntry = { businessId: string; customerName: string; customerPhone: string; serviceId: string; serviceName: string; date: string; status: 'waiting' | 'ready' | 'contacted' | 'booked' | 'closed'; createdAt: number; updatedAt: number };
type AppointmentLike = { customerId?: string; customerName: string; customerPhone: string; serviceId: string; serviceName: string; startsAt: string; endsAt: string; amount: number; status: string };
type DueRef = { businessId: string; communicationId: string; partition: string; dueAt: number };

const DEFAULT_SETTINGS: CommunicationSettings = { bookingConfirmation: true, reminder24h: true, morningReminder: true, reminder2h: false, reviewRequest: true, rebookReminder: true, noShowRecovery: true, waitlistRecovery: true, ownerPush: true, customerChannel: 'whatsapp_manual' };
const DEFAULT_POLICY: BookingPolicy = { depositRequired: false, depositType: 'fixed', depositValue: 0, cancellationHours: 24, noShowPolicyText: 'Please give at least 24 hours notice when cancelling or rescheduling.', collectionProvider: 'none' };
function safeText(value: unknown, max = 500) { return String(value ?? '').trim().slice(0, max); }
function partitionFor(timestamp: number) { return new Date(timestamp).toISOString().slice(0, 7); }
function previousPartition(month: string) { const [y, m] = month.split('-').map(Number); return new Date(Date.UTC(y, m - 2, 1)).toISOString().slice(0, 7); }
function nextPartition(month: string) { const [y, m] = month.split('-').map(Number); return new Date(Date.UTC(y, m, 1)).toISOString().slice(0, 7); }
function dueBucket(timestamp: number) { return new Date(timestamp).toISOString().slice(0, 13).replace(':', '-'); }
function commTable(businessId: string, partition: string) { return `communications:${businessId}:${partition}`; }
function waitlistTable(businessId: string, partition: string) { return `waitlist:${businessId}:${partition}`; }
function indexKey(value: string) { return value.replace(/[^a-zA-Z0-9_-]/g, '-').slice(0, 180); }
function commIndexPath(businessId: string, dedupeKey: string) { return `communication-index/${businessId}/${indexKey(dedupeKey)}.json`; }
function waitlistIndexPath(businessId: string, dedupeKey: string) { return `waitlist-index/${businessId}/${indexKey(dedupeKey)}.json`; }
function joziMs(localIso: string) { return new Date(`${localIso}+02:00`).getTime(); }
function friendlySlot(startsAt: string) { const [date, rawTime] = startsAt.split('T'); return `${date} at ${rawTime?.slice(0, 5) || ''}`; }
function boolInput(input: Record<string, unknown>, key: string, fallback: boolean) { return typeof input[key] === 'boolean' ? Boolean(input[key]) : fallback; }

export async function ensureCommunicationSettings(businessId: string) { const existing = (await db.list<CommunicationSettings>(`communication-settings:${businessId}`, { limit: 1 })).items[0]; if (existing) return existing; const [id] = await db.add(`communication-settings:${businessId}`, [DEFAULT_SETTINGS]); if (!id) throw new Error('Could not create communication settings'); return { id, ...DEFAULT_SETTINGS }; }
export async function saveCommunicationSettings(businessId: string, input: Record<string, unknown>) { const existing = await ensureCommunicationSettings(businessId); const next: CommunicationSettings = { bookingConfirmation: boolInput(input, 'bookingConfirmation', existing.bookingConfirmation), reminder24h: boolInput(input, 'reminder24h', existing.reminder24h), morningReminder: boolInput(input, 'morningReminder', existing.morningReminder), reminder2h: boolInput(input, 'reminder2h', existing.reminder2h), reviewRequest: boolInput(input, 'reviewRequest', existing.reviewRequest), rebookReminder: boolInput(input, 'rebookReminder', existing.rebookReminder), noShowRecovery: boolInput(input, 'noShowRecovery', existing.noShowRecovery), waitlistRecovery: boolInput(input, 'waitlistRecovery', existing.waitlistRecovery), ownerPush: boolInput(input, 'ownerPush', existing.ownerPush), customerChannel: 'whatsapp_manual' }; const { id } = existing; const [ok] = await db.update(`communication-settings:${businessId}`, [{ id, record: next }]); if (!ok) throw new Error('Could not save communication settings'); return { id, ...next }; }
export async function getBookingPolicy(businessId: string) { const existing = (await db.list<BookingPolicy>(`booking-policy:${businessId}`, { limit: 1 })).items[0]; if (existing) return existing; const [id] = await db.add(`booking-policy:${businessId}`, [DEFAULT_POLICY]); if (!id) throw new Error('Could not create booking policy'); return { id, ...DEFAULT_POLICY }; }
export async function saveBookingPolicy(businessId: string, input: Record<string, unknown>) { const existing = await getBookingPolicy(businessId); const depositType: BookingPolicy['depositType'] = input.depositType === 'percentage' ? 'percentage' : input.depositType === 'fixed' ? 'fixed' : existing.depositType; const rawValue = input.depositValue === undefined ? existing.depositValue : Number(input.depositValue); if (!Number.isFinite(rawValue) || rawValue < 0) throw new Error('Enter a valid deposit value'); if (depositType === 'percentage' && rawValue > 100) throw new Error('Deposit percentage cannot exceed 100%'); if (depositType === 'fixed' && rawValue > 10000) throw new Error('Deposit amount is too high'); const rawHours = input.cancellationHours === undefined ? existing.cancellationHours : Number(input.cancellationHours); if (!Number.isFinite(rawHours) || rawHours < 0 || rawHours > 168) throw new Error('Cancellation notice must be between 0 and 168 hours'); const next: BookingPolicy = { depositRequired: boolInput(input, 'depositRequired', existing.depositRequired), depositType, depositValue: rawValue, cancellationHours: rawHours, noShowPolicyText: safeText(input.noShowPolicyText ?? existing.noShowPolicyText, 500), collectionProvider: 'none' }; const { id } = existing; const [ok] = await db.update(`booking-policy:${businessId}`, [{ id, record: next }]); if (!ok) throw new Error('Could not save booking policy'); return { id, ...next }; }
export function depositForAmount(policy: BookingPolicy, amount: number) { if (!policy.depositRequired) return 0; return policy.depositType === 'percentage' ? Math.round(Math.max(0, amount) * policy.depositValue / 100) : Math.min(Math.max(0, amount), policy.depositValue); }

export async function notifyOwners(businessId: string, title: string, body: string) { try { const settings = await ensureCommunicationSettings(businessId); if (!settings.ownerPush) return; const team = await listTeam(businessId); const userIds = team.filter(member => member.role === 'owner' || member.role === 'manager').map(member => member.userId).filter(Boolean); if (!userIds.length) return; await notifications.send({ userIds, notification: { title, body, url: '#/app' }, data: { businessId, source: 'beauty-os' }, ttlSeconds: 3600 }); } catch (err) { console.warn('Owner notification failed', err); } }

async function scheduleCommunication(input: Omit<CommunicationRecord, 'status' | 'createdAt' | 'updatedAt'> & { dedupeKey: string }) { const indexPath = commIndexPath(input.businessId, input.dedupeKey); const [index] = await storage.read([indexPath]); if (index?.content) { try { return JSON.parse(index.content) as { id: string; partition: string; status?: CommunicationStatus }; } catch {} } const now = Date.now(); const partition = partitionFor(input.dueAt); await registerPartition(input.businessId,'communications',partition); const status: CommunicationStatus = input.dueAt <= now ? 'ready' : 'scheduled'; const { dedupeKey: _dedupeKey, ...rest } = input; const record: CommunicationRecord = { ...rest, status, createdAt: now, updatedAt: now }; const [id] = await db.add(commTable(input.businessId, partition), [record]); if (!id) throw new Error('Could not schedule communication'); await storage.write([{ path: indexPath, content: JSON.stringify({ id, partition }), contentType: 'application/json' }]); if (status === 'scheduled') await db.add(`communication-due:${dueBucket(input.dueAt)}`, [{ businessId: input.businessId, communicationId: id, partition, dueAt: input.dueAt }]); return { id, partition, status }; }
async function scheduleAndAlert(input: Omit<CommunicationRecord, 'status' | 'createdAt' | 'updatedAt'> & { dedupeKey: string }, title: string) { const result = await scheduleCommunication(input); if (result.status === 'ready') await notifyOwners(input.businessId, title, `${input.customerName} · ${input.kind.replace(/_/g, ' ')}`); return result; }

export async function scheduleConfirmedAppointment(businessId: string, businessName: string, appointmentId: string, appointment: AppointmentLike) { const settings = await ensureCommunicationSettings(businessId); const start = joziMs(appointment.startsAt); if (!Number.isFinite(start) || start <= Date.now()) return; const base = { businessId, customerId: appointment.customerId, appointmentId, customerName: appointment.customerName, customerPhone: appointment.customerPhone, channel: settings.customerChannel, automation: true } as const; if (settings.bookingConfirmation) await scheduleAndAlert({ ...base, kind: 'booking_confirmation', message: `Hi ${appointment.customerName}, your ${appointment.serviceName} appointment with ${businessName} is confirmed for ${friendlySlot(appointment.startsAt)}. Manage or request another time here: {{BOOKING_LINK}}`, dueAt: Date.now(), dedupeKey: `${appointmentId}:confirmation` }, 'Confirmation ready'); if (settings.reminder24h) await scheduleAndAlert({ ...base, kind: 'reminder_24h', message: `Hi ${appointment.customerName}, a reminder from ${businessName}: your ${appointment.serviceName} appointment is ${friendlySlot(appointment.startsAt)}. If you need to change it, please contact the studio as soon as possible.`, dueAt: start - 24 * 3600000, dedupeKey: `${appointmentId}:reminder24` }, '24-hour reminder ready'); if (settings.morningReminder) { const date = appointment.startsAt.slice(0, 10); const dueAt = new Date(`${date}T07:00:00+02:00`).getTime(); if (dueAt < start) await scheduleAndAlert({ ...base, kind: 'reminder_morning', message: `Good morning ${appointment.customerName}. ${businessName} is expecting you today for ${appointment.serviceName} at ${appointment.startsAt.slice(11, 16)}.`, dueAt, dedupeKey: `${appointmentId}:morning` }, 'Morning reminder ready'); } if (settings.reminder2h) await scheduleAndAlert({ ...base, kind: 'reminder_2h', message: `Hi ${appointment.customerName}, your ${appointment.serviceName} appointment with ${businessName} is in about 2 hours at ${appointment.startsAt.slice(11, 16)}.`, dueAt: start - 2 * 3600000, dedupeKey: `${appointmentId}:reminder2` }, '2-hour reminder ready'); }
export async function scheduleCompletionFollowups(businessId: string, businessName: string, appointmentId: string, appointment: AppointmentLike, rebookDays: number) { const settings = await ensureCommunicationSettings(businessId); const base = { businessId, customerId: appointment.customerId, appointmentId, customerName: appointment.customerName, customerPhone: appointment.customerPhone, channel: settings.customerChannel, automation: true } as const; if (settings.reviewRequest) await scheduleCommunication({ ...base, kind: 'review_request', message: `Hi ${appointment.customerName}, thank you for visiting ${businessName}. If you were happy with your ${appointment.serviceName}, we would really appreciate your feedback.`, dueAt: Date.now() + 18 * 3600000, dedupeKey: `${appointmentId}:review` }); if (settings.rebookReminder) await scheduleCommunication({ ...base, kind: 'rebook_reminder', message: `Hi ${appointment.customerName}, you may be due for your next ${appointment.serviceName} with ${businessName}. You can request a time here: {{BOOKING_LINK}}`, dueAt: joziMs(appointment.startsAt) + Math.max(7, Math.min(120, rebookDays || 21)) * 86400000, dedupeKey: `${appointmentId}:rebook` }); }
async function updateIndexedCommunication(businessId: string, dedupeKey: string, status: CommunicationStatus) { const [idx] = await storage.read([commIndexPath(businessId, dedupeKey)]); if (!idx?.content) return; try { const parsed = JSON.parse(idx.content) as { id: string; partition: string }; const [record] = await db.get<CommunicationRecord>(commTable(businessId, parsed.partition), [parsed.id]); if (!record || !['scheduled', 'ready'].includes(record.status)) return; await db.update(commTable(businessId, parsed.partition), [{ id: parsed.id, record: { ...record, status, updatedAt: Date.now() } }]); } catch {} }
export async function cancelAppointmentCommunications(businessId: string, appointmentId: string) { for (const suffix of ['confirmation', 'reminder24', 'morning', 'reminder2', 'review', 'rebook']) await updateIndexedCommunication(businessId, `${appointmentId}:${suffix}`, 'cancelled'); }
export async function queueNoShowRecovery(businessId: string, businessName: string, appointmentId: string, appointment: AppointmentLike) { await cancelAppointmentCommunications(businessId, appointmentId); const settings = await ensureCommunicationSettings(businessId); if (!settings.noShowRecovery) return; await scheduleAndAlert({ businessId, customerId: appointment.customerId, appointmentId, customerName: appointment.customerName, customerPhone: appointment.customerPhone, kind: 'no_show_recovery', channel: settings.customerChannel, message: `Hi ${appointment.customerName}, we missed you at ${businessName} today. If you would like to reschedule your ${appointment.serviceName}, you can request a new time here: {{BOOKING_LINK}}`, dueAt: Date.now(), automation: true, dedupeKey: `${appointmentId}:noshow` }, 'No-show recovery ready'); }
export async function queueCancellation(businessId: string, businessName: string, appointmentId: string, appointment: AppointmentLike) { await cancelAppointmentCommunications(businessId, appointmentId); const settings = await ensureCommunicationSettings(businessId); if (settings.bookingConfirmation) await scheduleAndAlert({ businessId, customerId: appointment.customerId, appointmentId, customerName: appointment.customerName, customerPhone: appointment.customerPhone, kind: 'booking_cancelled', channel: settings.customerChannel, message: `Hi ${appointment.customerName}, your ${appointment.serviceName} appointment with ${businessName} for ${friendlySlot(appointment.startsAt)} has been cancelled. You can request another time here: {{BOOKING_LINK}}`, dueAt: Date.now(), automation: true, dedupeKey: `${appointmentId}:cancelled` }, 'Cancellation message ready'); await wakeWaitlist(businessId, businessName, appointmentId, appointment); }

export async function addWaitlistEntry(businessId: string, input: { customerName: string; customerPhone: string; serviceId: string; serviceName: string; date: string }) { const partition = input.date.slice(0, 7); await registerPartition(businessId,'waitlist',partition); const dedupeKey = `${input.customerPhone}:${input.serviceId}:${input.date}`; const path = waitlistIndexPath(businessId, dedupeKey); const [existing] = await storage.read([path]); if (existing?.content) { try { return JSON.parse(existing.content) as { id: string; partition: string }; } catch {} } const now = Date.now(); const record: WaitlistEntry = { businessId, customerName: safeText(input.customerName, 80), customerPhone: safeText(input.customerPhone, 30), serviceId: safeText(input.serviceId, 120), serviceName: safeText(input.serviceName, 120), date: input.date, status: 'waiting', createdAt: now, updatedAt: now }; const [id] = await db.add(waitlistTable(businessId, partition), [record]); if (!id) throw new Error('Could not join the waitlist'); await storage.write([{ path, content: JSON.stringify({ id, partition }), contentType: 'application/json' }]); return { id, partition }; }
export async function listWaitlist(businessId: string, partition: string) { return (await db.list<WaitlistEntry>(waitlistTable(businessId, partition), { limit: 200 })).items; }
async function wakeWaitlist(businessId: string, businessName: string, appointmentId: string, appointment: AppointmentLike) { const settings = await ensureCommunicationSettings(businessId); if (!settings.waitlistRecovery) return; const partition = appointment.startsAt.slice(0, 7); const date = appointment.startsAt.slice(0, 10); const entries = (await listWaitlist(businessId, partition)).filter(entry => entry.status === 'waiting' && entry.date === date && entry.serviceId === appointment.serviceId).slice(0, 5); for (const entry of entries) { const result = await scheduleAndAlert({ businessId, waitlistId: entry.id, waitlistPartition: partition, customerName: entry.customerName, customerPhone: entry.customerPhone, kind: 'waitlist_opening', channel: settings.customerChannel, message: `Hi ${entry.customerName}, a ${entry.serviceName} slot has opened with ${businessName} on ${entry.date}. If you would like it, request the available time here: {{BOOKING_LINK}}`, dueAt: Date.now(), automation: true, dedupeKey: `${appointmentId}:waitlist:${entry.id}` }, 'Waitlist opportunity ready'); if (result.id) { const { id, ...rest } = entry; await db.update(waitlistTable(businessId, partition), [{ id, record: { ...rest, status: 'ready', updatedAt: Date.now() } }]); } } }

export async function listRecentCommunications(businessId: string, partition: string) { const previous = previousPartition(partition); const next = nextPartition(partition); const [currentRows, previousRows, nextRows] = await Promise.all([db.list<CommunicationRecord>(commTable(businessId, partition), { limit: 250 }), db.list<CommunicationRecord>(commTable(businessId, previous), { limit: 250 }), db.list<CommunicationRecord>(commTable(businessId, next), { limit: 250 })]); return [...currentRows.items.map(item => ({ ...item, partition })), ...previousRows.items.map(item => ({ ...item, partition: previous })), ...nextRows.items.map(item => ({ ...item, partition: next }))].sort((a, b) => b.dueAt - a.dueAt).slice(0, 400); }
export async function markCommunicationHandedOff(businessId: string, partition: string, id: string) { if (!/^\d{4}-\d{2}$/.test(partition)) throw new Error('Communication partition is required'); const [record] = await db.get<CommunicationRecord>(commTable(businessId, partition), [id]); if (!record) throw new Error('Communication not found'); if (record.status !== 'ready') return { id, ...record, partition }; const next: CommunicationRecord = { ...record, status: 'handed_off', handedOffAt: Date.now(), updatedAt: Date.now() }; const [ok] = await db.update(commTable(businessId, partition), [{ id, record: next }]); if (!ok) throw new Error('Could not update communication'); if (record.waitlistId && record.waitlistPartition) { const [wait] = await db.get<WaitlistEntry>(waitlistTable(businessId, record.waitlistPartition), [record.waitlistId]); if (wait) await db.update(waitlistTable(businessId, record.waitlistPartition), [{ id: record.waitlistId, record: { ...wait, status: 'contacted', updatedAt: Date.now() } }]); } return { id, ...next, partition }; }

async function processDueBucket(bucket: string) { const table = `communication-due:${bucket}`; const page = await db.list<DueRef>(table, { limit: 500 }); const now = Date.now(); for (const ref of page.items) { if (ref.dueAt > now) continue; const [record] = await db.get<CommunicationRecord>(commTable(ref.businessId, ref.partition), [ref.communicationId]); if (!record) { await db.delete(table, [ref.id]); continue; } if (record.status === 'scheduled') { const next: CommunicationRecord = { ...record, status: 'ready', updatedAt: now }; await db.update(commTable(ref.businessId, ref.partition), [{ id: ref.communicationId, record: next }]); await notifyOwners(ref.businessId, 'Client follow-up ready', `${record.customerName} · ${record.kind.replace(/_/g, ' ')}`); } await db.delete(table, [ref.id]); } }
export async function runCommunicationSweep() { const now = Date.now(); const buckets = [0, 1, 2].map(hours => dueBucket(now - hours * 3600000)); for (const bucket of buckets) await processDueBucket(bucket); }
