import { db } from '@appdeploy/sdk';

export type PlanId = 'solo' | 'studio' | 'pro';
export type SubscriptionStatus = 'trial' | 'active' | 'grace' | 'suspended' | 'cancelled';
export type Plan = { id: PlanId; name: string; description: string; limits: { staffSeats: number; services: number; clients: number; locations: number }; features: { growth: boolean; insights: boolean; team: boolean; customDomain: boolean; multiLocation: boolean } };
export type Subscription = { businessId: string; planId: PlanId; status: SubscriptionStatus; billingProvider: string; billingEnforced: boolean; externalCustomerId: string; externalSubscriptionId: string; trialStartedAt: number; trialEndsAt: number; currentPeriodEndsAt: number | null; graceEndsAt: number | null; cancelAtPeriodEnd: boolean; createdAt: number; updatedAt: number };
export type TeamMember = { userId: string; email: string; name: string; role: 'owner' | 'manager' | 'staff'; joinedAt: number };
export const TRIAL_DAYS = 30;
export const GRACE_DAYS = 7;
export const PLAN_CATALOG: Plan[] = [
  { id: 'solo', name: 'Solo', description: 'For one independent salon, barber or personal-care professional running one location.', limits: { staffSeats: 1, services: 25, clients: 500, locations: 1 }, features: { growth: true, insights: true, team: false, customDomain: false, multiLocation: false } },
  { id: 'studio', name: 'Studio', description: 'For a growing salon, barbershop or studio with a small team and shared operations.', limits: { staffSeats: 5, services: 100, clients: 3000, locations: 1 }, features: { growth: true, insights: true, team: true, customDomain: false, multiLocation: false } },
  { id: 'pro', name: 'Pro', description: 'For established teams preparing for branches and a custom domain.', limits: { staffSeats: 15, services: 250, clients: 10000, locations: 3 }, features: { growth: true, insights: true, team: true, customDomain: true, multiLocation: true } },
];
export function planById(value: unknown): Plan { return PLAN_CATALOG.find(plan => plan.id === value) || PLAN_CATALOG[0]; }
export function isPlanId(value: unknown): value is PlanId { return PLAN_CATALOG.some(plan => plan.id === value); }
async function subscriptionRow(businessId: string) { return (await db.list<Subscription>(`subscriptions:${businessId}`, { limit: 1 })).items[0] || null; }
export async function ensureSubscription(businessId: string, requestedPlan: PlanId = 'solo') { const existing = await subscriptionRow(businessId); if (existing) return existing; const now = Date.now(); const record: Subscription = { businessId, planId: requestedPlan, status: 'trial', billingProvider: 'none', billingEnforced: false, externalCustomerId: '', externalSubscriptionId: '', trialStartedAt: now, trialEndsAt: now + TRIAL_DAYS * 86400000, currentPeriodEndsAt: null, graceEndsAt: null, cancelAtPeriodEnd: false, createdAt: now, updatedAt: now }; const [id] = await db.add(`subscriptions:${businessId}`, [record]); if (!id) throw new Error('Could not create subscription'); return { id, ...record }; }
function effectiveState(subscription: Subscription) { if (subscription.status === 'suspended' || subscription.status === 'cancelled') return subscription.status; if (!subscription.billingEnforced) return subscription.status; const now = Date.now(); if (subscription.status === 'trial' && now > subscription.trialEndsAt) return now <= subscription.trialEndsAt + GRACE_DAYS * 86400000 ? 'grace' : 'suspended'; if (subscription.status === 'grace' && subscription.graceEndsAt && now > subscription.graceEndsAt) return 'suspended'; return subscription.status; }
export async function getEntitlements(businessId: string) { const subscription = await ensureSubscription(businessId); const plan = planById(subscription.planId); const effectiveStatus = effectiveState(subscription); const [team, services, clients] = await Promise.all([db.list<TeamMember>(`team:${businessId}`, { limit: plan.limits.staffSeats + 1 }), db.list(`services:${businessId}`, { limit: plan.limits.services + 1 }), db.list(`customers:${businessId}`, { limit: plan.limits.clients + 1 })]); const canWrite = !['suspended', 'cancelled'].includes(effectiveStatus); return { subscription, plan, effectiveStatus, billingPreview: !subscription.billingEnforced, canWrite, canBook: canWrite, limits: plan.limits, features: plan.features, usage: { staffSeats: team.items.length, services: services.items.length, clients: clients.items.length, locations: 1 } }; }
export async function changePreviewPlan(businessId: string, planId: PlanId) { const subscription = await ensureSubscription(businessId); if (subscription.billingEnforced) throw new Error('Plan changes must be handled by the connected billing provider'); if (['suspended', 'cancelled'].includes(subscription.status)) throw new Error('This subscription cannot change plan'); const { id, ...record } = subscription; const [ok] = await db.update(`subscriptions:${businessId}`, [{ id, record: { ...record, planId, updatedAt: Date.now() } }]); if (!ok) throw new Error('Could not change plan'); return ensureSubscription(businessId); }
export async function setSubscriptionStatus(businessId: string, status: SubscriptionStatus) { const subscription = await ensureSubscription(businessId); const { id, ...record } = subscription; const [ok] = await db.update(`subscriptions:${businessId}`, [{ id, record: { ...record, status, updatedAt: Date.now() } }]); if (!ok) throw new Error('Could not update subscription status'); return ensureSubscription(businessId); }
export async function ensureOwnerTeam(businessId: string, user: { userId: string; email?: string; name?: string }) { const team = (await db.list<TeamMember>(`team:${businessId}`, { limit: 30 })).items; if (team.some(member => member.userId === user.userId)) return team; await db.add(`team:${businessId}`, [{ userId: user.userId, email: user.email || '', name: user.name || 'Owner', role: 'owner', joinedAt: Date.now() }]); return (await db.list<TeamMember>(`team:${businessId}`, { limit: 30 })).items; }
export async function listTeam(businessId: string) { return (await db.list<TeamMember>(`team:${businessId}`, { limit: 30 })).items; }
export async function addTeamMember(businessId: string, member: TeamMember) { const access = await getEntitlements(businessId); const team = await listTeam(businessId); if (!access.features.team) throw new Error('Team access requires the Studio or Pro plan'); if (team.some(item => item.userId === member.userId)) return team.find(item => item.userId === member.userId)!; if (team.length >= access.limits.staffSeats) throw new Error('This plan has reached its team seat limit'); const [id] = await db.add(`team:${businessId}`, [member]); if (!id) throw new Error('Could not add team member'); return { id, ...member }; }
