import { db, storage } from '@appdeploy/sdk';

export type PartitionKind='appointments'|'communications'|'waitlist'|'attribution'|'growth-responses';
export type PrivacyRequest={requestType:'access'|'correction'|'deletion'|'objection';name:string;phone:string;email:string;details:string;status:'verification_required'|'in_review'|'completed'|'declined';ownerNote:string;createdAt:number;updatedAt:number};
export type ComplianceIncident={category:'privacy'|'security'|'customer_complaint'|'other';severity:'low'|'medium'|'high';summary:string;details:string;status:'open'|'in_review'|'closed';createdAt:number;updatedAt:number};
export type PlatformConfig={productName:string;operatorLegalName:string;privacyEmail:string;supportEmail:string;informationOfficer:string;legalAddress:string;paiaManualUrl:string;privacyVersion:string;termsVersion:string;updatedAt:number};
type PartitionRecord={kind:PartitionKind;month:string;createdAt:number};
type TeamMember={userId:string};
type ExportJob={status:'queued'|'running'|'ready'|'failed';tables:string[];tableIndex:number;nextToken:string;page:number;files:string[];manifestPath:string;queueId:string;createdAt:number;updatedAt:number;error:string};
type DeletionJob={status:'scheduled'|'purging'|'cancelled';purgeAfter:number;previousSubscriptionStatus:string;tables:string[];tableIndex:number;storagePrefixes:string[];storageIndex:number;memberUserIds:string[];memberIndex:number;queueId:string;slug:string;createdAt:number;updatedAt:number};
type QueueRef={businessId:string;jobId:string;createdAt:number;purgeAfter?:number};
const DAY=86400000;
const DEFAULT_CONFIG:PlatformConfig={productName:'Glow Hub',operatorLegalName:'',privacyEmail:'',supportEmail:'',informationOfficer:'',legalAddress:'',paiaManualUrl:'',privacyVersion:'2026-09-03-draft',termsVersion:'2026-09-03-draft',updatedAt:0};
function safeText(v:unknown,max=500){return String(v??'').trim().slice(0,max)}
function key(v:string){return v.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,160)}
function validEmail(v:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
function monthOk(v:string){return /^\d{4}-\d{2}$/.test(v)}
async function deleteTablePage(table:string){const page=await db.list(table,{limit:200});if(page.items.length)await db.delete(table,page.items.map(item=>item.id));return page.items.length<200}
export async function registerPartition(businessId:string,kind:PartitionKind,month:string){if(!businessId||!monthOk(month))return;const path=`partition-index/${businessId}/${kind}-${month}.json`;const [existing]=await storage.read([path]);if(existing?.content)return;const [id]=await db.add(`partitions:${businessId}`,[{kind,month,createdAt:Date.now()}]);if(id)await storage.write([{path,content:JSON.stringify({id}),contentType:'application/json'}])}
async function partitions(businessId:string){return (await db.list<PartitionRecord>(`partitions:${businessId}`,{limit:240})).items}
export async function getPlatformConfig(){const existing=(await db.list<PlatformConfig>('platform-config',{limit:1})).items[0];if(!existing)return DEFAULT_CONFIG;return['Beauty Business OS','Beauty & Grooming OS'].includes(existing.productName)?{...existing,productName:'Glow Hub'}:existing}
export async function savePlatformConfig(input:Record<string,unknown>){const existing=(await db.list<PlatformConfig>('platform-config',{limit:1})).items[0];const next:PlatformConfig={productName:safeText(input.productName,80)||'Glow Hub',operatorLegalName:safeText(input.operatorLegalName,140),privacyEmail:safeText(input.privacyEmail,160).toLowerCase(),supportEmail:safeText(input.supportEmail,160).toLowerCase(),informationOfficer:safeText(input.informationOfficer,120),legalAddress:safeText(input.legalAddress,240),paiaManualUrl:safeText(input.paiaManualUrl,500),privacyVersion:safeText(input.privacyVersion,40)||'draft',termsVersion:safeText(input.termsVersion,40)||'draft',updatedAt:Date.now()};if(next.privacyEmail&&!validEmail(next.privacyEmail))throw new Error('Enter a valid privacy email');if(next.supportEmail&&!validEmail(next.supportEmail))throw new Error('Enter a valid support email');if(existing){const{id}=existing;const[ok]=await db.update('platform-config',[{id,record:next}]);if(!ok)throw new Error('Could not save platform legal settings')}else{const[id]=await db.add('platform-config',[next]);if(!id)throw new Error('Could not save platform legal settings')}return next}
export async function getPublicLegalConfig(){const config=await getPlatformConfig();const blockers:string[]=[];if(!config.operatorLegalName)blockers.push('Platform legal entity');if(!config.privacyEmail)blockers.push('Privacy contact');if(!config.informationOfficer)blockers.push('Information Officer');if(!config.legalAddress)blockers.push('Legal address');if(!config.paiaManualUrl)blockers.push('PAIA manual/link');return{...config,commercialLaunchReady:blockers.length===0,blockers}}
export async function createPrivacyRequest(businessId:string,input:Record<string,unknown>){const requestType=['access','correction','deletion','objection'].includes(String(input.requestType))?String(input.requestType) as PrivacyRequest['requestType']:'access';const name=safeText(input.name,100),phone=safeText(input.phone,40),email=safeText(input.email,160).toLowerCase(),details=safeText(input.details,1200);if(name.length<2||(!phone&&!validEmail(email)))throw new Error('Provide your name and a phone number or valid email');if(email&&!validEmail(email))throw new Error('Enter a valid email');const day=new Date().toISOString().slice(0,10);const contact=key((email||phone).toLowerCase());const path=`privacy-request-index/${businessId}/${day}/${contact}-${requestType}.json`;const[duplicate]=await storage.read([path]);if(duplicate?.content)throw new Error('A similar request was already received today');const now=Date.now();const record:PrivacyRequest={requestType,name,phone,email,details,status:'verification_required',ownerNote:'',createdAt:now,updatedAt:now};const[id]=await db.add(`privacy-requests:${businessId}`,[record]);if(!id)throw new Error('Could not record the request');await storage.write([{path,content:JSON.stringify({id}),contentType:'application/json'}]);return{id,...record}}
export async function listPrivacyRequests(businessId:string){return (await db.list<PrivacyRequest>(`privacy-requests:${businessId}`,{limit:100})).items.sort((a,b)=>b.createdAt-a.createdAt)}
export async function updatePrivacyRequest(businessId:string,id:string,input:Record<string,unknown>){const[existing]=await db.get<PrivacyRequest>(`privacy-requests:${businessId}`,[id]);if(!existing)throw new Error('Privacy request not found');const status=['verification_required','in_review','completed','declined'].includes(String(input.status))?String(input.status) as PrivacyRequest['status']:existing.status;const next={...existing,status,ownerNote:safeText(input.ownerNote??existing.ownerNote,800),updatedAt:Date.now()};const[ok]=await db.update(`privacy-requests:${businessId}`,[{id,record:next}]);if(!ok)throw new Error('Could not update privacy request');return{id,...next}}
export async function reportIncident(businessId:string,input:Record<string,unknown>){const category=['privacy','security','customer_complaint','other'].includes(String(input.category))?String(input.category) as ComplianceIncident['category']:'other';const severity=['low','medium','high'].includes(String(input.severity))?String(input.severity) as ComplianceIncident['severity']:'medium';const summary=safeText(input.summary,160),details=safeText(input.details,1600);if(summary.length<5||details.length<10)throw new Error('Describe the incident and what happened');const now=Date.now();const record:ComplianceIncident={category,severity,summary,details,status:'open',createdAt:now,updatedAt:now};const[id]=await db.add(`compliance-incidents:${businessId}`,[record]);if(!id)throw new Error('Could not record incident');return{id,...record}}
export async function listIncidents(businessId:string){return(await db.list<ComplianceIncident>(`compliance-incidents:${businessId}`,{limit:100})).items.sort((a,b)=>b.createdAt-a.createdAt)}
export async function updateIncident(businessId:string,id:string,status:string){const[existing]=await db.get<ComplianceIncident>(`compliance-incidents:${businessId}`,[id]);if(!existing)throw new Error('Incident not found');if(!['open','in_review','closed'].includes(status))throw new Error('Invalid incident status');const next={...existing,status:status as ComplianceIncident['status'],updatedAt:Date.now()};const[ok]=await db.update(`compliance-incidents:${businessId}`,[{id,record:next}]);if(!ok)throw new Error('Could not update incident');return{id,...next}}
export async function writeAudit(businessId:string,actorId:string,action:string,detail=''){await db.add(`audit:${businessId}`,[{actorId:safeText(actorId,100),action:safeText(action,100),detail:safeText(detail,300),createdAt:Date.now()}])}
export async function getTenantLaunchReadiness(businessId:string,business:{category?:string;name:string;whatsapp:string;location:string;about:string;bookingEnabled:boolean}){const[services,settings,portfolio,reviews,communications,legal]=await Promise.all([db.list(`services:${businessId}`,{limit:2}),db.list<{heroImagePath?:string;logoImagePath?:string}>(`storefront-settings:${businessId}`,{limit:1}),db.list(`portfolio:${businessId}`,{limit:4}),db.list(`reviews:${businessId}`,{limit:2}),db.list(`communication-settings:${businessId}`,{limit:1}),getPublicLegalConfig()]);const checks=[{id:'profile',label:'Business profile complete',ok:Boolean(business.name&&business.whatsapp&&business.location&&business.about)},{id:'category',label:'Business type selected',ok:Boolean(business.category)},{id:'service',label:'At least one published service',ok:services.items.length>0},{id:'booking',label:'Public booking enabled',ok:business.bookingEnabled},{id:'hero',label:'Hero image uploaded',ok:Boolean(settings.items[0]?.heroImagePath)},{id:'portfolio',label:'At least three portfolio examples',ok:portfolio.items.length>=3},{id:'reviews',label:'At least one review published',ok:reviews.items.length>0},{id:'communications',label:'Communication automation configured',ok:communications.items.length>0}];const score=Math.round(checks.filter(item=>item.ok).length/checks.length*100);return{score,checks,technicalReady:score===100,commercialBlockers:legal.blockers,commercialLaunchReady:score===100&&legal.commercialLaunchReady}}
export async function getDeletionJob(businessId:string){return(await db.list<DeletionJob>(`deletion-jobs:${businessId}`,{limit:1})).items[0]||null}
export async function createDeletionJob(businessId:string,slug:string,previousSubscriptionStatus:string){const existing=await getDeletionJob(businessId);if(existing&&['scheduled','purging'].includes(existing.status))return existing;const[parts,team]=await Promise.all([partitions(businessId),db.list<TeamMember>(`team:${businessId}`,{limit:30})]);const fixed=[`services:${businessId}`,`customers:${businessId}`,`campaigns:${businessId}`,`growth-schedules:${businessId}`,`team:${businessId}`,`subscriptions:${businessId}`,`storefront-settings:${businessId}`,`business-hours:${businessId}`,`publishing-settings:${businessId}`,`meta-connections:${businessId}`,`meta-oauth-states:${businessId}`,`meta-page-candidates:${businessId}`,`meta-whatsapp-candidates:${businessId}`,`meta-whatsapp-templates:${businessId}`,`meta-publications:${businessId}`,`portfolio:${businessId}`,`reviews:${businessId}`,`communication-settings:${businessId}`,`booking-policy:${businessId}`,`privacy-requests:${businessId}`,`compliance-incidents:${businessId}`,`audit:${businessId}`,`partitions:${businessId}`,`export-jobs:${businessId}`];const partitionTables=parts.map(p=>`${p.kind}:${businessId}:${p.month}`);const now=Date.now(),purgeAfter=now+30*DAY;const record:DeletionJob={status:'scheduled',purgeAfter,previousSubscriptionStatus,tables:[...new Set([...fixed,...partitionTables])],tableIndex:0,storagePrefixes:[`tenant-media/${businessId}/`,`indexes/${businessId}/`,`communication-index/${businessId}/`,`waitlist-index/${businessId}/`,`partition-index/${businessId}/`,`privacy-request-index/${businessId}/`,`exports/${businessId}/`],storageIndex:0,memberUserIds:[...new Set(team.items.map(m=>m.userId).filter(Boolean))],memberIndex:0,queueId:'',slug,createdAt:now,updatedAt:now};const[jobId]=await db.add(`deletion-jobs:${businessId}`,[record]);if(!jobId)throw new Error('Could not schedule deletion');const[queueId]=await db.add('deletion-queue',[{businessId,jobId,purgeAfter,createdAt:now}]);if(!queueId)throw new Error('Could not queue deletion');const[ok]=await db.update(`deletion-jobs:${businessId}`,[{id:jobId,record:{...record,queueId}}]);if(!ok)throw new Error('Could not finalise deletion schedule');return{id:jobId,...record,queueId}}
export async function cancelDeletionJob(businessId:string){const job=await getDeletionJob(businessId);if(!job||!['scheduled','purging'].includes(job.status))throw new Error('No reversible closure is scheduled');if(job.status==='purging'||Date.now()>=job.purgeAfter)throw new Error('Permanent purge has already started');if(job.queueId)await db.delete('deletion-queue',[job.queueId]);const{id,...record}=job;const next={...record,status:'cancelled' as const,updatedAt:Date.now()};await db.update(`deletion-jobs:${businessId}`,[{id,record:next}]);return{id,...next}}
export async function startExportJob(businessId:string,business:Record<string,unknown>){const active=(await db.list<ExportJob>(`export-jobs:${businessId}`,{limit:10})).items.find(j=>['queued','running'].includes(j.status));if(active)return active;const parts=await partitions(businessId);const tables=[`subscriptions:${businessId}`,`services:${businessId}`,`customers:${businessId}`,`campaigns:${businessId}`,`growth-schedules:${businessId}`,`team:${businessId}`,`storefront-settings:${businessId}`,`business-hours:${businessId}`,`portfolio:${businessId}`,`reviews:${businessId}`,`communication-settings:${businessId}`,`booking-policy:${businessId}`,`privacy-requests:${businessId}`,`compliance-incidents:${businessId}`,`audit:${businessId}`,...parts.map(p=>`${p.kind}:${businessId}:${p.month}`)];const now=Date.now(),base=`exports/${businessId}/${now}`;const businessPath=`${base}/business.json`;await storage.write([{path:businessPath,content:JSON.stringify({exportedAt:new Date(now).toISOString(),business}),contentType:'application/json'}]);const record:ExportJob={status:'queued',tables:[...new Set(tables)],tableIndex:0,nextToken:'',page:0,files:[businessPath],manifestPath:`${base}/manifest.json`,queueId:'',createdAt:now,updatedAt:now,error:''};const[jobId]=await db.add(`export-jobs:${businessId}`,[record]);if(!jobId)throw new Error('Could not create export job');const[queueId]=await db.add('export-queue',[{businessId,jobId,createdAt:now}]);if(!queueId)throw new Error('Could not queue export');await db.update(`export-jobs:${businessId}`,[{id:jobId,record:{...record,queueId}}]);return{id:jobId,...record,queueId}}
export async function listExportJobs(businessId:string){return(await db.list<ExportJob>(`export-jobs:${businessId}`,{limit:10})).items.sort((a,b)=>b.createdAt-a.createdAt)}
export async function getExportDownloads(businessId:string,jobId:string){const[job]=await db.get<ExportJob>(`export-jobs:${businessId}`,[jobId]);if(!job)throw new Error('Export job not found');if(job.status!=='ready')return{id:jobId,...job,downloads:[]};const media=await storage.list({prefix:`tenant-media/${businessId}/`,limit:100});const paths=[job.manifestPath,...job.files,...media.paths];const urls=await storage.url(paths);return{id:jobId,...job,downloads:urls}}
async function processExport(ref:QueueRef&{id:string}){const[job]=await db.get<ExportJob>(`export-jobs:${ref.businessId}`,[ref.jobId]);if(!job){await db.delete('export-queue',[ref.id]);return}if(job.status==='ready'||job.status==='failed'){await db.delete('export-queue',[ref.id]);return}const id=ref.jobId,record=job;if(record.tableIndex>=record.tables.length){const manifest={createdAt:new Date(record.createdAt).toISOString(),completedAt:new Date().toISOString(),files:record.files,mediaPrefix:`tenant-media/${ref.businessId}/`};await storage.write([{path:record.manifestPath,content:JSON.stringify(manifest,null,2),contentType:'application/json'}]);await db.update(`export-jobs:${ref.businessId}`,[{id,record:{...record,status:'ready',updatedAt:Date.now()}}]);await db.delete('export-queue',[ref.id]);return}const table=record.tables[record.tableIndex];try{const page=await db.list(table,{limit:200,nextToken:record.nextToken||undefined});const files=[...record.files];if(page.items.length){const path=`exports/${ref.businessId}/${record.createdAt}/${String(record.tableIndex).padStart(3,'0')}-${String(record.page).padStart(3,'0')}.json`;const[ok]=await storage.write([{path,content:JSON.stringify({table,items:page.items}),contentType:'application/json'}]);if(!ok)throw new Error('Could not write export page');files.push(path)}const next=page.nextToken?{...record,status:'running' as const,nextToken:page.nextToken,page:record.page+1,files,updatedAt:Date.now()}:{...record,status:'running' as const,tableIndex:record.tableIndex+1,nextToken:'',page:0,files,updatedAt:Date.now()};await db.update(`export-jobs:${ref.businessId}`,[{id,record:next}])}catch(err){await db.update(`export-jobs:${ref.businessId}`,[{id,record:{...record,status:'failed',error:err instanceof Error?err.message:'Export failed',updatedAt:Date.now()}}]);await db.delete('export-queue',[ref.id])}}
async function processDeletion(ref:QueueRef&{id:string}){if(!ref.purgeAfter||ref.purgeAfter>Date.now())return;const[job]=await db.get<DeletionJob>(`deletion-jobs:${ref.businessId}`,[ref.jobId]);if(!job){await db.delete('deletion-queue',[ref.id]);return}if(job.status==='cancelled'){await db.delete('deletion-queue',[ref.id]);return}const id=ref.jobId,record=job;const running={...record,status:'purging' as const,updatedAt:Date.now()};if(running.tableIndex<running.tables.length){const done=await deleteTablePage(running.tables[running.tableIndex]);await db.update(`deletion-jobs:${ref.businessId}`,[{id,record:{...running,tableIndex:done?running.tableIndex+1:running.tableIndex}}]);return}if(running.storageIndex<running.storagePrefixes.length){const prefix=running.storagePrefixes[running.storageIndex];const page=await storage.list({prefix,limit:200});if(page.paths.length)await storage.delete(page.paths);await db.update(`deletion-jobs:${ref.businessId}`,[{id,record:{...running,storageIndex:page.paths.length<200?running.storageIndex+1:running.storageIndex}}]);return}if(running.memberIndex<running.memberUserIds.length){const userId=running.memberUserIds[running.memberIndex];const memberships=await db.list<{businessId:string}>(`memberships:${userId}`,{limit:20});const ids=memberships.items.filter(m=>m.businessId===ref.businessId).map(m=>m.id);if(ids.length)await db.delete(`memberships:${userId}`,ids);await db.update(`deletion-jobs:${ref.businessId}`,[{id,record:{...running,memberIndex:running.memberIndex+1}}]);return}await storage.delete([`storefronts/${running.slug}.json`]);await db.delete('businesses',[ref.businessId]);await db.delete('deletion-queue',[ref.id]);await db.delete(`deletion-jobs:${ref.businessId}`,[id])}
export async function runLaunchMaintenance(){const[exports,deletions]=await Promise.all([db.list<QueueRef>('export-queue',{limit:3}),db.list<QueueRef>('deletion-queue',{limit:10})]);for(const ref of exports.items)await processExport(ref);for(const ref of deletions.items)await processDeletion(ref);const heartbeat=(await db.list<{lastRunAt:number}>('launch-maintenance-heartbeat',{limit:1})).items[0];const record={lastRunAt:Date.now()};if(heartbeat)await db.update('launch-maintenance-heartbeat',[{id:heartbeat.id,record}]);else await db.add('launch-maintenance-heartbeat',[record])}
export async function getSystemHealth(){const heartbeat=(await db.list<{lastRunAt:number}>('launch-maintenance-heartbeat',{limit:1})).items[0];return{ok:true,maintenanceLastRunAt:heartbeat?.lastRunAt||null,maintenanceHealthy:heartbeat?Date.now()-heartbeat.lastRunAt<3600000:true}}
export async function getTenantCompliance(businessId:string,business:{category?:string;name:string;whatsapp:string;location:string;about:string;bookingEnabled:boolean}){const[launchReadiness,privacyRequests,incidents,deletionJob,exportJobs]=await Promise.all([getTenantLaunchReadiness(businessId,business),listPrivacyRequests(businessId),listIncidents(businessId),getDeletionJob(businessId),listExportJobs(businessId)]);return{launchReadiness,privacyRequests,incidents,deletionJob,exportJobs}}
export async function getPlatformOverview(){const[businesses,deletions,heartbeat,legal]=await Promise.all([db.list<Record<string,unknown>>('businesses',{limit:200}),db.list<QueueRef>('deletion-queue',{limit:100}),db.list<{lastRunAt:number}>('launch-maintenance-heartbeat',{limit:1}),getPublicLegalConfig()]);return{businesses:businesses.items.map(b=>({id:b.id,name:b.name,slug:b.slug,status:b.status,createdAt:b.createdAt})),deletions:deletions.items,legal,maintenanceLastRunAt:heartbeat.items[0]?.lastRunAt||null,truncated:Boolean(businesses.nextToken)}}
