import { db,error,json,requireAuth,router,storage } from '@appdeploy/sdk';
import { getEntitlements } from './entitlements';
import { writeAudit } from './launch-readiness';

type Role='owner'|'manager'|'staff';
type Member={businessId:string;role:Role;businessName:string};
type Business={slug:string};
type Service={name:string;price:number;duration:number;description:string;active:boolean;rebookDays:number;createdAt:number;updatedAt?:number};
type Portfolio={serviceId?:string;serviceName?:string;updatedAt?:number};
type Campaign={serviceId?:string;serviceName?:string;updatedAt?:number};
type PublicStorefront={services:Array<Service&{id:string}>;portfolio?:Array<Record<string,unknown>&{serviceId?:string;serviceName?:string}>};

function safeText(value:unknown,max=300){return String(value??'').trim().slice(0,max)}
function cleanSlug(value:string){return String(value||'').toLowerCase().trim().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)}
async function memberships(userId:string){return(await db.list<Member>(`memberships:${userId}`,{limit:20})).items}
async function requireManager(userId:string,businessId:string){return(await memberships(userId)).find(m=>m.businessId===businessId&&['owner','manager'].includes(m.role))||null}
async function activeServices(businessId:string){return(await db.list<Service>(`services:${businessId}`,{limit:100})).items.filter(s=>s.active!==false)}
async function refreshPublicStorefront(businessId:string){const[business]=await db.get<Business>('businesses',[businessId]);if(!business?.slug)return;const path=`storefronts/${cleanSlug(business.slug)}.json`,[file]=await storage.read([path]);if(!file?.content)return;try{const storefront=JSON.parse(file.content) as PublicStorefront;const services=await activeServices(businessId);const names=new Map(services.map(s=>[s.id,s.name]));storefront.services=services;storefront.portfolio=(storefront.portfolio||[]).map(item=>item.serviceId&&names.has(item.serviceId)?{...item,serviceName:names.get(item.serviceId)}:item);await storage.write([{path,content:JSON.stringify(storefront),contentType:'application/json'}])}catch(err){console.warn('service storefront refresh skipped',err)}}
async function syncLinkedNames(businessId:string,serviceId:string,name:string){const portfolio=await db.list<Portfolio>(`portfolio:${businessId}`,{limit:100}),portfolioUpdates=portfolio.items.filter(x=>x.serviceId===serviceId).map(({id,...record})=>({id,record:{...record,serviceName:name,updatedAt:Date.now()}}));if(portfolioUpdates.length)await db.update(`portfolio:${businessId}`,portfolioUpdates);const campaigns=await db.list<Campaign>(`campaigns:${businessId}`,{limit:100}),campaignUpdates=campaigns.items.filter(x=>x.serviceId===serviceId).map(({id,...record})=>({id,record:{...record,serviceName:name,updatedAt:Date.now()}}));if(campaignUpdates.length)await db.update(`campaigns:${businessId}`,campaignUpdates)}

export const serviceManagementHandler=router({
  'PUT /api/services/:id':[requireAuth(),async({user,params,body})=>{const i=body as Record<string,unknown>,businessId=safeText(i.businessId,100);if(!(await requireManager(user!.userId,businessId)))return error('You do not have permission to edit services',403);const access=await getEntitlements(businessId);if(!access.canWrite)return error('Subscription access is paused',403);const[existing]=await db.get<Service>(`services:${businessId}`,[params.id]);if(!existing||existing.active===false)return error('Service not found',404);const name=safeText(i.name,80);if(name.length<2)return error('Service name is required',400);const price=Number(i.price),duration=Number(i.duration),rebookDays=Number(i.rebookDays);if(!Number.isFinite(price)||price<0)return error('Choose a valid price',400);if(!Number.isFinite(duration)||duration<15||duration>480)return error('Choose a valid duration',400);const next:Service={...existing,name,price,duration,description:safeText(i.description,500),rebookDays:Number.isFinite(rebookDays)?Math.max(7,Math.min(120,rebookDays)):existing.rebookDays,updatedAt:Date.now()};const[ok]=await db.update(`services:${businessId}`,[{id:params.id,record:next}]);if(!ok)return error('Service could not be updated',500);await syncLinkedNames(businessId,params.id,name);await refreshPublicStorefront(businessId);await writeAudit(businessId,user!.userId,'service_updated',params.id);return json({id:params.id,...next})}],
  'DELETE /api/services/:id':[requireAuth(),async({user,params,body})=>{const i=body as Record<string,unknown>,businessId=safeText(i.businessId,100);if(!(await requireManager(user!.userId,businessId)))return error('You do not have permission to delete services',403);const access=await getEntitlements(businessId);if(!access.canWrite)return error('Subscription access is paused',403);const services=await activeServices(businessId),existing=services.find(s=>s.id===params.id);if(!existing)return error('Service not found',404);if(services.length<=1)return error('Add another service before deleting your only bookable service',409);await db.delete(`services:${businessId}`,[params.id]);await refreshPublicStorefront(businessId);await writeAudit(businessId,user!.userId,'service_deleted',params.id);return json({ok:true})}]
});
