import { db, storage } from '@appdeploy/sdk';
import { registerPartition } from './launch-readiness';

export type ThemeId = 'editorial' | 'soft-luxe' | 'minimal';
export type AccentId = 'rose' | 'plum' | 'sand' | 'ink';
export type StorefrontSeed = { name: string; slug: string; tagline: string; about: string; location: string; category?: string };
export type StorefrontSettings = { theme: ThemeId; accent: AccentId; seoTitle: string; seoDescription: string; heroImagePath: string; logoImagePath: string; requestedDomain: string; domainStatus: 'not_requested' | 'requested'; createdAt: number; updatedAt: number };
export type PublicBrand = { theme: ThemeId; accent: AccentId; seoTitle: string; seoDescription: string; heroImagePath?: string; logoImagePath?: string; heroImageUrl?: string; logoImageUrl?: string; requestedDomain?: string; domainStatus?: 'not_requested' | 'requested' };
export type PortfolioKind = 'completed' | 'before_after'; export type PortfolioRecord = { kind?: PortfolioKind; title: string; description: string; serviceId: string; serviceName: string; imagePath?: string; beforeImagePath?: string; afterImagePath?: string; published: boolean; createdAt: number; updatedAt: number };
export type PublicPortfolioItem = PortfolioRecord & { id: string; imageUrl?: string; beforeImageUrl?: string; afterImageUrl?: string };
export type ReviewRecord = { customerName: string; quote: string; rating: number; source: string; published: boolean; createdAt: number; updatedAt: number };
export type PublicReview = ReviewRecord & { id: string };
export type AttributionEvent = { event: 'campaign_view' | 'booking_start' | 'booking_request'; campaignId: string; serviceId: string; createdAt: number };
export type AttributionSummary = { campaignViews: number; bookingStarts: number; bookingRequests: number; byCampaign: Array<{ campaignId: string; views: number; starts: number; requests: number }>; truncated: boolean };

const THEMES: ThemeId[] = ['editorial', 'soft-luxe', 'minimal'];
const ACCENTS: AccentId[] = ['rose', 'plum', 'sand', 'ink'];
function defaultTheme(category=''):ThemeId { if(category==='barber')return 'editorial'; if(['beauty_salon','nail_studio','lash_brow','spa'].includes(category))return 'soft-luxe'; return 'minimal'; }
function defaultAccent(category=''):AccentId { if(category==='barber')return 'ink'; if(category==='spa')return 'sand'; if(category==='hair_salon')return 'plum'; return 'rose'; }
function safeText(value: unknown, max = 300) { return String(value ?? '').trim().slice(0, max); }
function domainPath(host: string) { return `domain-map/${host}.json`; }
function normalizeDomain(value: unknown) { const host = safeText(value, 253).toLowerCase().replace(/^https?:\/\//, '').split('/')[0].replace(/\.$/, ''); if (!host) return ''; if (!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host) || host.endsWith('.appdeploy.ai')) throw new Error('Enter a valid custom domain'); return host; }
function extFor(contentType: string) { return contentType === 'image/png' ? 'png' : contentType === 'image/webp' ? 'webp' : 'jpg'; }
function validateImage(base64: string, contentType: string) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(contentType)) throw new Error('Use a JPG, PNG or WebP image'); if (!base64 || base64.length > 5000000 || !/^[A-Za-z0-9+/=]+$/.test(base64)) throw new Error('Image is invalid or too large'); }
async function signedUrls(paths: string[]) { const unique = [...new Set(paths.filter(Boolean))]; const map = new Map<string, string>(); if (!unique.length) return map; try { const rows = await storage.url(unique); rows.forEach(row => map.set(row.path, row.url)); } catch (err) { console.warn('Media URL hydration failed', err); } return map; }

export async function ensureStorefrontSettings(businessId: string, seed: StorefrontSeed) { const existing = (await db.list<StorefrontSettings>(`storefront-settings:${businessId}`, { limit: 1 })).items[0]; if (existing) return existing; const now = Date.now(); const record: StorefrontSettings = { theme: defaultTheme(seed.category), accent: defaultAccent(seed.category), seoTitle: safeText(`${seed.name} | ${seed.location}`, 70), seoDescription: safeText(seed.about || seed.tagline, 180), heroImagePath: '', logoImagePath: '', requestedDomain: '', domainStatus: 'not_requested', createdAt: now, updatedAt: now }; const [id] = await db.add(`storefront-settings:${businessId}`, [record]); if (!id) throw new Error('Could not create storefront settings'); return { id, ...record }; }
export async function saveStorefrontSettings(businessId: string, seed: StorefrontSeed, input: Record<string, unknown>, customDomainAllowed: boolean) { const existing = await ensureStorefrontSettings(businessId, seed); const theme = THEMES.includes(input.theme as ThemeId) ? input.theme as ThemeId : existing.theme; const accent = ACCENTS.includes(input.accent as AccentId) ? input.accent as AccentId : existing.accent; const requestedDomain = normalizeDomain(input.requestedDomain ?? existing.requestedDomain); if (requestedDomain && !customDomainAllowed) throw new Error('Custom domains require the Pro plan'); if (requestedDomain && requestedDomain !== existing.requestedDomain) { const [mapped] = await storage.read([domainPath(requestedDomain)]); if (mapped?.content) { try { const owner = JSON.parse(mapped.content) as { businessId?: string }; if (owner.businessId && owner.businessId !== businessId) throw new Error('That domain is already assigned to another business'); } catch (err) { if (err instanceof Error && err.message.includes('already assigned')) throw err; } } const [written] = await storage.write([{ path: domainPath(requestedDomain), content: JSON.stringify({ businessId, slug: seed.slug }), contentType: 'application/json' }]); if (!written) throw new Error('Could not reserve custom domain'); } const next: StorefrontSettings = { theme, accent, seoTitle: safeText(input.seoTitle ?? existing.seoTitle, 70) || safeText(seed.name, 70), seoDescription: safeText(input.seoDescription ?? existing.seoDescription, 180) || safeText(seed.about || seed.tagline, 180), heroImagePath: existing.heroImagePath, logoImagePath: existing.logoImagePath, requestedDomain, domainStatus: requestedDomain ? 'requested' : 'not_requested', createdAt: existing.createdAt, updatedAt: Date.now() }; const { id } = existing; const [ok] = await db.update(`storefront-settings:${businessId}`, [{ id, record: next }]); if (!ok) { if (requestedDomain && requestedDomain !== existing.requestedDomain) await storage.delete([domainPath(requestedDomain)]); throw new Error('Could not save storefront settings'); } if (existing.requestedDomain && existing.requestedDomain !== requestedDomain) await storage.delete([domainPath(existing.requestedDomain)]); return { id, ...next }; }
export async function syncDomainEntitlement(businessId: string, seed: StorefrontSeed, allowed: boolean) { const settings = await ensureStorefrontSettings(businessId, seed); if (!settings.requestedDomain) return; if (!allowed) { await storage.delete([domainPath(settings.requestedDomain)]); return; } const [ok] = await storage.write([{ path: domainPath(settings.requestedDomain), content: JSON.stringify({ businessId, slug: seed.slug }), contentType: 'application/json' }]); if (!ok) throw new Error('Could not activate domain mapping'); }
export async function releaseDomainMapping(businessId: string, seed: StorefrontSeed) { const settings = await ensureStorefrontSettings(businessId, seed); if (!settings.requestedDomain) return; const [mapped] = await storage.read([domainPath(settings.requestedDomain)]); if (!mapped?.content) return; try { const value = JSON.parse(mapped.content) as { businessId?: string }; if (value.businessId === businessId) await storage.delete([domainPath(settings.requestedDomain)]); } catch {} }
export async function resolveDomain(host: string) { const normalized = normalizeDomain(host); if (!normalized) return null; const [mapped] = await storage.read([domainPath(normalized)]); if (!mapped?.content) return null; try { const value = JSON.parse(mapped.content) as { businessId?: string; slug?: string }; return value.businessId && value.slug ? value : null; } catch { return null; } }

export async function uploadBrandImage(businessId: string, seed: StorefrontSeed, kind: 'hero' | 'logo', base64: string, contentType: string) { validateImage(base64, contentType); const existing = await ensureStorefrontSettings(businessId, seed); const path = `tenant-media/${businessId}/brand/${kind}-${Date.now()}.${extFor(contentType)}`; const [written] = await storage.write([{ path, content: base64, contentType }]); if (!written) throw new Error('Could not store image'); const oldPath = kind === 'hero' ? existing.heroImagePath : existing.logoImagePath; const { id, ...record } = existing; const next = { ...record, [kind === 'hero' ? 'heroImagePath' : 'logoImagePath']: path, updatedAt: Date.now() } as StorefrontSettings; const [ok] = await db.update(`storefront-settings:${businessId}`, [{ id, record: next }]); if (!ok) { await storage.delete([path]); throw new Error('Could not attach image to storefront'); } if (oldPath) await storage.delete([oldPath]); const urls = await signedUrls([path]); return { ...next, id, [`${kind}ImageUrl`]: urls.get(path) || '' };
}
export async function createPortfolioItem(businessId: string, input: { kind?: PortfolioKind; title: string; description: string; serviceId: string; serviceName: string; imageBase64?: string; contentType?: string; beforeImageBase64?: string; beforeContentType?: string; afterImageBase64?: string; afterContentType?: string }) { const kind:PortfolioKind=input.kind==='before_after'?'before_after':'completed';const current=await db.list<PortfolioRecord>(`portfolio:${businessId}`,{limit:61});if(current.items.length>=60)throw new Error('Portfolio limit reached');const title=safeText(input.title,100);if(title.length<2)throw new Error('Portfolio title is required');if(kind==='before_after'){validateImage(input.beforeImageBase64||'',input.beforeContentType||'');validateImage(input.afterImageBase64||'',input.afterContentType||'');if((input.beforeImageBase64?.length||0)+(input.afterImageBase64?.length||0)>7000000)throw new Error('Before and after images are too large together')}else validateImage(input.imageBase64||'',input.contentType||'');const token=`${Date.now()}-${Math.random().toString(36).slice(2,9)}`,imagePath=kind==='completed'?`tenant-media/${businessId}/portfolio/${token}-work.${extFor(input.contentType||'image/jpeg')}`:'',beforeImagePath=kind==='before_after'?`tenant-media/${businessId}/portfolio/${token}-before.${extFor(input.beforeContentType||'image/jpeg')}`:'',afterImagePath=kind==='before_after'?`tenant-media/${businessId}/portfolio/${token}-after.${extFor(input.afterContentType||'image/jpeg')}`:'';const uploads=kind==='before_after'?[{path:beforeImagePath,content:input.beforeImageBase64||'',contentType:input.beforeContentType||'image/jpeg'},{path:afterImagePath,content:input.afterImageBase64||'',contentType:input.afterContentType||'image/jpeg'}]:[{path:imagePath,content:input.imageBase64||'',contentType:input.contentType||'image/jpeg'}];const written=await storage.write(uploads);if(written.some(ok=>!ok)){const done=uploads.filter((_,i)=>written[i]).map(x=>x.path);if(done.length)await storage.delete(done);throw new Error('Could not store portfolio media')}const now=Date.now();const record:PortfolioRecord={kind,title,description:safeText(input.description,400),serviceId:safeText(input.serviceId,120),serviceName:safeText(input.serviceName,120),...(imagePath?{imagePath}:{}),...(beforeImagePath?{beforeImagePath}:{}),...(afterImagePath?{afterImagePath}:{}),published:true,createdAt:now,updatedAt:now};const[id]=await db.add(`portfolio:${businessId}`,[record]);if(!id){await storage.delete(uploads.map(x=>x.path));throw new Error('Could not save portfolio item')}const urls=await signedUrls(uploads.map(x=>x.path));return{id,...record,imageUrl:imagePath?urls.get(imagePath)||'':'',beforeImageUrl:beforeImagePath?urls.get(beforeImagePath)||'':'',afterImageUrl:afterImagePath?urls.get(afterImagePath)||'':''};
}
export async function deletePortfolioItem(businessId: string, id: string) { const[record]=await db.get<PortfolioRecord>(`portfolio:${businessId}`,[id]);if(!record)throw new Error('Portfolio item not found');const[deleted]=await db.delete(`portfolio:${businessId}`,[id]);if(!deleted)throw new Error('Could not delete portfolio item');const paths=[record.imagePath,record.beforeImagePath,record.afterImagePath].filter((value):value is string=>Boolean(value));if(paths.length)await storage.delete(paths); }
export async function createReview(businessId: string, input: Record<string, unknown>) { const rows = await db.list<ReviewRecord>(`reviews:${businessId}`, { limit: 51 }); if (rows.items.length >= 50) throw new Error('Review limit reached'); const customerName = safeText(input.customerName, 80), quote = safeText(input.quote, 500), source = safeText(input.source, 40) || 'Direct'; const rating = Math.max(1, Math.min(5, Math.round(Number(input.rating || 5)))); if (customerName.length < 2 || quote.length < 8) throw new Error('Reviewer name and testimonial are required'); const now = Date.now(); const record: ReviewRecord = { customerName, quote, rating, source, published: true, createdAt: now, updatedAt: now }; const [id] = await db.add(`reviews:${businessId}`, [record]); if (!id) throw new Error('Could not save review'); return { id, ...record }; }
export async function deleteReview(businessId: string, id: string) { const [deleted] = await db.delete(`reviews:${businessId}`, [id]); if (!deleted) throw new Error('Review not found'); }

export async function getPublicMarketplaceProjection(businessId: string, seed: StorefrontSeed) { const [settings, portfolioRows, reviewRows] = await Promise.all([ensureStorefrontSettings(businessId, seed), db.list<PortfolioRecord>(`portfolio:${businessId}`, { limit: 60 }), db.list<ReviewRecord>(`reviews:${businessId}`, { limit: 50 })]); const brand: PublicBrand = { theme: settings.theme, accent: settings.accent, seoTitle: settings.seoTitle, seoDescription: settings.seoDescription, heroImagePath: settings.heroImagePath || undefined, logoImagePath: settings.logoImagePath || undefined, requestedDomain: settings.requestedDomain || undefined, domainStatus: settings.domainStatus }; return { brand, portfolio: portfolioRows.items.filter(item => item.published).sort((a, b) => b.createdAt - a.createdAt), reviews: reviewRows.items.filter(item => item.published).sort((a, b) => b.createdAt - a.createdAt) };
}
export async function hydratePublicStorefrontMedia<T extends { brand?: PublicBrand; portfolio: PublicPortfolioItem[] }>(storefront: T): Promise<T> { const paths=[storefront.brand?.heroImagePath||'',storefront.brand?.logoImagePath||'',...storefront.portfolio.flatMap(item=>[item.imagePath||'',item.beforeImagePath||'',item.afterImagePath||''])];const urls=await signedUrls(paths);const brand=storefront.brand?{...storefront.brand,heroImageUrl:storefront.brand.heroImagePath?urls.get(storefront.brand.heroImagePath)||'':'',logoImageUrl:storefront.brand.logoImagePath?urls.get(storefront.brand.logoImagePath)||'':''}:storefront.brand;const portfolio=storefront.portfolio.map(item=>({...item,kind:item.kind||'completed',imageUrl:item.imagePath?urls.get(item.imagePath)||'':'',beforeImageUrl:item.beforeImagePath?urls.get(item.beforeImagePath)||'':'',afterImageUrl:item.afterImagePath?urls.get(item.afterImagePath)||'':''}));return{...storefront,brand,portfolio};
}
export async function recordAttribution(businessId: string, event: AttributionEvent['event'], campaignId: string, serviceId: string) { if (!campaignId) return; const month = new Date(Date.now() + 2 * 3600000).toISOString().slice(0, 7); await registerPartition(businessId,'attribution',month); await db.add(`attribution:${businessId}:${month}`, [{ event, campaignId: safeText(campaignId, 120), serviceId: safeText(serviceId, 120), createdAt: Date.now() }]); }
export async function getAttributionSummary(businessId: string, month: string): Promise<AttributionSummary> { const rows = await db.list<AttributionEvent>(`attribution:${businessId}:${month}`, { limit: 1000 }); const by = new Map<string, { campaignId: string; views: number; starts: number; requests: number }>(); for (const item of rows.items) { const current = by.get(item.campaignId) || { campaignId: item.campaignId, views: 0, starts: 0, requests: 0 }; if (item.event === 'campaign_view') current.views++; if (item.event === 'booking_start') current.starts++; if (item.event === 'booking_request') current.requests++; by.set(item.campaignId, current); } const values = [...by.values()].sort((a, b) => b.requests - a.requests || b.views - a.views); return { campaignViews: values.reduce((sum, row) => sum + row.views, 0), bookingStarts: values.reduce((sum, row) => sum + row.starts, 0), bookingRequests: values.reduce((sum, row) => sum + row.requests, 0), byCampaign: values, truncated: Boolean(rows.nextToken) };
}
export async function getOwnerMarketplace(businessId: string, seed: StorefrontSeed, month: string) { const[settings,portfolioRows,reviewRows,attribution]=await Promise.all([ensureStorefrontSettings(businessId,seed),db.list<PortfolioRecord>(`portfolio:${businessId}`,{limit:60}),db.list<ReviewRecord>(`reviews:${businessId}`,{limit:50}),getAttributionSummary(businessId,month)]);const paths=[settings.heroImagePath,settings.logoImagePath,...portfolioRows.items.flatMap(item=>[item.imagePath||'',item.beforeImagePath||'',item.afterImagePath||''])];const urls=await signedUrls(paths);return{storefrontSettings:{...settings,heroImageUrl:settings.heroImagePath?urls.get(settings.heroImagePath)||'':'',logoImageUrl:settings.logoImagePath?urls.get(settings.logoImagePath)||'':''},portfolio:portfolioRows.items.sort((a,b)=>b.createdAt-a.createdAt).map(item=>({...item,kind:item.kind||'completed',imageUrl:item.imagePath?urls.get(item.imagePath)||'':'',beforeImageUrl:item.beforeImagePath?urls.get(item.beforeImagePath)||'':'',afterImageUrl:item.afterImagePath?urls.get(item.afterImagePath)||'':''})),reviews:reviewRows.items.sort((a,b)=>b.createdAt-a.createdAt),attribution};
}
export async function getMarketplaceExport(businessId: string, seed: StorefrontSeed, month: string) { const [settings, portfolio, reviews, attribution] = await Promise.all([ensureStorefrontSettings(businessId, seed), db.list<PortfolioRecord>(`portfolio:${businessId}`, { limit: 60 }), db.list<ReviewRecord>(`reviews:${businessId}`, { limit: 50 }), getAttributionSummary(businessId, month)]); return { storefrontSettings: settings, portfolio: portfolio.items, reviews: reviews.items, attribution };
}
