import { useEffect,useMemo,useState } from 'react';
import { api } from '@appdeploy/client';
import { ArrowRight,Clock3,MapPin,Menu,MessageCircle,Star,X } from 'lucide-react';
import PremiumStorefrontHome from './PremiumStorefront';
import './public-profile.css';

type Theme='editorial'|'soft-luxe'|'minimal';type DayKey='mon'|'tue'|'wed'|'thu'|'fri'|'sat'|'sun';
type Service={id:string;name:string;price:number;duration:number;description:string};
type Portfolio={id:string;kind?:'completed'|'before_after';title:string;description:string;serviceId:string;serviceName:string;imageUrl?:string;beforeImageUrl?:string;afterImageUrl?:string};
type Review={id:string;customerName:string;quote:string;rating:number;source:string};
type Storefront={businessId:string;category?:string;name:string;ownerName:string;slug:string;whatsapp:string;location:string;tagline:string;about:string;services:Service[];portfolio:Portfolio[];reviews?:Review[];brand?:{theme?:Theme;accent?:string;heroImageUrl?:string;heroImageUrls?:string[];logoImageUrl?:string;seoTitle?:string;seoDescription?:string};businessHours?:{timezone:string;days:Record<DayKey,{enabled:boolean;open:string;close:string}>}};
type Page='home'|'services'|'portfolio'|'reviews'|'about';
function money(v:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v||0)}
function whatsappNumber(phone:string){let d=phone.replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('27'))return d;if(d.startsWith('0')&&d.length===10)return`27${d.slice(1)}`;if(d.length===9)return`27${d}`;return d}
function wa(phone:string,text:string){return`https://wa.me/${whatsappNumber(phone)}?text=${encodeURIComponent(text)}`}
function titleFor(s:Storefront,page:Page){if(page==='services')return`Services | ${s.name}`;if(page==='portfolio')return`Portfolio | ${s.name}`;if(page==='reviews')return`Reviews | ${s.name}`;if(page==='about')return`About | ${s.name}`;return s.brand?.seoTitle||s.name}
export default function PublicProfile({slug,page}:{slug:string;page:Page}){const[s,setS]=useState<Storefront|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);Promise.all([api.get(`/api/storefront/${encodeURIComponent(slug)}`),api.get(`/api/hero-gallery-public/${encodeURIComponent(slug)}`).catch(()=>({data:{urls:[]}}))]).then(([storefront,gallery])=>{if(!active)return;const base=storefront.data as Storefront,setUrls=(gallery.data.urls||[]) as string[];setS({...base,brand:{...(base.brand||{}),heroImageUrls:setUrls.length?setUrls:(base.brand?.heroImageUrl?[base.brand.heroImageUrl]:[])}})}).catch(()=>active&&setS(null)).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug]);useEffect(()=>{if(!s)return;document.title=titleFor(s,page);window.scrollTo({top:0,left:0,behavior:'auto'})},[s,page]);if(loading)return <div className='public-loading'>Opening…</div>;if(!s)return <div className='public-empty'><h1>This page isn’t available.</h1><p>Try returning to Discover and choosing the business again.</p><a href='#/'>Back to Discover</a></div>;const skin=`storefront-shell sf-theme-${s.brand?.theme||'editorial'} sf-accent-${s.brand?.accent||'rose'}`;return <div className={`${skin} public-profile`}><PublicHeader s={s}/>{page==='services'?<ServicesDirectory s={s}/>:page==='portfolio'?<PortfolioDirectory s={s}/>:page==='reviews'?<ReviewsDirectory s={s}/>:page==='about'?<AboutDirectory s={s}/>:<PremiumStorefrontHome s={s}/>}<PublicFooter s={s}/></div>}
function PublicHeader({s}:{s:Storefront}){const[open,setOpen]=useState(false),identity=s.brand?.logoImageUrl?<img src={s.brand.logoImageUrl} className='public-logo' alt={`${s.name} logo`}/>:<span className='public-name'>{s.name}</span>;const close=()=>setOpen(false);return <header className='public-header'><div className='public-header-inner'><a href={`#/${s.slug}`} className='public-identity'>{identity}</a><nav className='public-desktop-nav'><a href={`#/${s.slug}/services`}>Services</a>{s.portfolio.length>0&&<a href={`#/${s.slug}/portfolio`}>Portfolio</a>}{(s.reviews?.length||0)>0&&<a href={`#/${s.slug}/reviews`}>Reviews</a>}<a href={`#/${s.slug}/about`}>About</a><a className='public-book' href={`#/${s.slug}/book`}>Book</a></nav><button className='public-menu-button' aria-label='Open menu' onClick={()=>setOpen(true)}><Menu size={19}/></button></div>{open&&<div className='public-menu-backdrop' onClick={close}><div className='public-menu-sheet' onClick={e=>e.stopPropagation()}><div className='public-menu-head'><a href={`#/${s.slug}`} onClick={close}>{identity}</a><button onClick={close} aria-label='Close menu'><X size={18}/></button></div><nav><a onClick={close} href={`#/${s.slug}/services`}>Services <ArrowRight size={15}/></a>{s.portfolio.length>0&&<a onClick={close} href={`#/${s.slug}/portfolio`}>Portfolio <ArrowRight size={15}/></a>}{(s.reviews?.length||0)>0&&<a onClick={close} href={`#/${s.slug}/reviews`}>Reviews <ArrowRight size={15}/></a>}<a onClick={close} href={`#/${s.slug}/about`}>About <ArrowRight size={15}/></a><a onClick={close} className='primary' href={`#/${s.slug}/book`}>Book an appointment</a></nav></div></div>}</header>}
function PageIntro({kicker,title,text}:{kicker:string;title:string;text?:string}){return <div className='public-page-intro'><p>{kicker}</p><h1>{title}</h1>{text&&<span>{text}</span>}</div>}
function ServicesDirectory({s}:{s:Storefront}){return <main className='public-page'><a href={`#/${s.slug}`} className='public-back'>← Back to {s.name}</a><PageIntro kicker='Services' title='Choose your service.' text={`${s.services.length} service${s.services.length===1?'':'s'}`}/><div className='public-service-grid'>{s.services.map(service=><article className='public-service-card' key={service.id}><a href={`#/${s.slug}/service/${service.id}`} className='public-service-main'><div className='public-service-top'><h2>{service.name}</h2><b>{money(service.price)}</b></div>{service.description&&<p>{service.description}</p>}<span><Clock3 size={14}/>{service.duration} min</span><strong>See photos & details <ArrowRight size={15}/></strong></a><a href={`#/${s.slug}/book?service=${service.id}`} className='public-service-book'>Book</a></article>)}</div></main>}
function portfolioImages(s:Storefront){return s.portfolio.flatMap(item=>{const rows:Array<{key:string;url:string;title:string;service:string;note:string}>=[];if(item.beforeImageUrl)rows.push({key:`${item.id}-before`,url:item.beforeImageUrl,title:`${item.title} · Before`,service:item.serviceName,note:item.description});if(item.afterImageUrl)rows.push({key:`${item.id}-after`,url:item.afterImageUrl,title:`${item.title} · After`,service:item.serviceName,note:item.description});if(item.imageUrl)rows.push({key:item.id,url:item.imageUrl,title:item.title,service:item.serviceName,note:item.description});return rows})}
function PortfolioDirectory({s}:{s:Storefront}){const images=useMemo(()=>portfolioImages(s),[s]);return <main className='public-page'><a href={`#/${s.slug}`} className='public-back'>← Back to {s.name}</a><PageIntro kicker='Portfolio' title='See the work.' text={`${images.length} photo${images.length===1?'':'s'}`}/>{images.length?<div className='public-portfolio-grid'>{images.map((item,index)=><figure key={item.key} className={`public-portfolio-item item-${index%7}`}><img src={item.url} alt={item.title} loading={index<3?'eager':'lazy'}/><figcaption><span>{item.service}</span><b>{item.title}</b>{item.note&&<small>{item.note}</small>}</figcaption></figure>)}</div>:<div className='public-none'>No photos have been added yet.</div>}</main>}
function ReviewsDirectory({s}:{s:Storefront}){const reviews=s.reviews||[],rating=reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:0;return <main className='public-page'><a href={`#/${s.slug}`} className='public-back'>← Back to {s.name}</a><PageIntro kicker='Reviews' title={reviews.length?'What clients are saying.':'Reviews coming soon.'} text={reviews.length?`${rating.toFixed(1)} · ${reviews.length} review${reviews.length===1?'':'s'}`:undefined}/><div className='public-review-grid'>{reviews.map(r=><article key={r.id}><div>{Array.from({length:r.rating}).map((_,i)=><Star key={i} size={14} fill='currentColor'/>)}</div><blockquote>“{r.quote}”</blockquote><b>{r.customerName}</b><span>{r.source}</span></article>)}</div></main>}
function AboutDirectory({s}:{s:Storefront}){const hero=s.brand?.heroImageUrls?.[0]||s.brand?.heroImageUrl;return <main className='public-page'><a href={`#/${s.slug}`} className='public-back'>← Back to {s.name}</a><div className='public-about-grid'><div><PageIntro kicker='About' title={s.name}/><p className='public-about-copy'>{s.about||`${s.name} is based in ${s.location}.`}</p><p className='public-location'><MapPin size={16}/>{s.location}</p><div className='public-about-actions'><a href={`#/${s.slug}/book`} className='public-book'>Book an appointment</a><a href={wa(s.whatsapp,`Hi ${s.ownerName}, I’d like to ask about an appointment at ${s.name}.`)} target='_blank' rel='noreferrer'><MessageCircle size={15}/>WhatsApp</a></div></div><div className='public-about-media'>{hero?<img src={hero} alt={s.name}/>:<span>{s.name}</span>}</div></div></main>}
function PublicFooter({s}:{s:Storefront}){return <footer className='public-footer'><div><b>{s.name}</b><span>{s.location}</span></div><nav><a href={`#/${s.slug}/services`}>Services</a>{s.portfolio.length>0&&<a href={`#/${s.slug}/portfolio`}>Portfolio</a>}<a href={`#/${s.slug}/about`}>About</a><a href={`#/${s.slug}/book`}>Book</a><a href={`#/${s.slug}/privacy`}>Privacy</a></nav></footer>}
