import { FormEvent,useMemo,useState } from 'react';
import { api } from '@appdeploy/client';
import { Loader2,Plus,Trash2 } from 'lucide-react';

type Service={id:string;name:string;price:number;duration:number;description:string;rebookDays:number;active?:boolean};
type Props={w:{business:{id:string};services:Service[]};refresh:()=>void};
type FormState={name:string;price:string;duration:string;description:string;rebookDays:string};
const blank:FormState={name:'',price:'',duration:'60',description:'',rebookDays:'21'};
const durations=[15,30,45,60,75,90,120,150,180,240,300,360,480];
const rebookOptions=[7,14,21,28,35,42,56,84,120];
function money(v:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v||0)}
function messageOf(error:unknown){const e=error as{response?:{data?:{error?:string}};message?:string};return e.response?.data?.error||e.message||'Something went wrong. Please try again.'}
function field(label:string,child:React.ReactNode){return <label className='block min-w-0'><span className='label'>{label}</span>{child}</label>}
function toForm(s:Service):FormState{return{name:s.name,price:String(s.price),duration:String(s.duration),description:s.description||'',rebookDays:String(s.rebookDays||21)}}
export function ServicesSimple({w,refresh}:Props){
  const services=useMemo(()=>w.services.filter(s=>s.active!==false),[w.services]);
  const[adding,setAdding]=useState(false),[editingId,setEditingId]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[form,setForm]=useState<FormState>(blank),[editForm,setEditForm]=useState<FormState>(blank);
  async function add(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await api.post('/api/services',{businessId:w.business.id,name:form.name,price:Number(form.price),duration:Number(form.duration),description:form.description,rebookDays:Number(form.rebookDays)});setForm(blank);setAdding(false);setMsg('Service added.');await refresh()}catch(error){setMsg(messageOf(error))}finally{setBusy(false)}}
  function beginEdit(s:Service){setAdding(false);setEditingId(s.id);setEditForm(toForm(s));setMsg('')}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!editingId)return;setBusy(true);setMsg('');try{await api.put(`/api/services/${editingId}`,{businessId:w.business.id,name:editForm.name,price:Number(editForm.price),duration:Number(editForm.duration),description:editForm.description,rebookDays:Number(editForm.rebookDays)});setEditingId('');setMsg('Service updated. Your storefront and linked work were refreshed.');await refresh()}catch(error){setMsg(messageOf(error))}finally{setBusy(false)}}
  async function remove(s:Service){const last=services.length===1,message=last?`Delete ${s.name}? Your business will temporarily stop appearing in Discover until you add another bookable service. Existing appointment history stays intact.`:`Delete ${s.name}? Existing appointment history will stay intact, but clients will no longer be able to book this service.`;if(!window.confirm(message))return;setBusy(true);setMsg('');try{const r=await api.delete(`/api/services/${s.id}`,{businessId:w.business.id});if(editingId===s.id)setEditingId('');setMsg((r.data?.remainingServices??Math.max(0,services.length-1))===0?'Service removed. Add a new service when you are ready to appear in Discover again.':'Service removed from bookings and your storefront.');await refresh()}catch(error){setMsg(messageOf(error))}finally{setBusy(false)}}
  const serviceForm=(value:FormState,setValue:(v:FormState)=>void,submit:(e:FormEvent)=>void,submitLabel:string)=><form onSubmit={submit} className='mt-5 grid gap-4 rounded-[26px] border border-stone-200 bg-white p-5 shadow-[0_14px_38px_rgba(35,28,31,.05)] md:grid-cols-2'>{field('Service name',<input required className='input' value={value.name} onChange={e=>setValue({...value,name:e.target.value})} placeholder='Classic cut, Braids, Facial…'/>)}{field('Price (R)',<input required min='0' type='number' className='input' value={value.price} onChange={e=>setValue({...value,price:e.target.value})}/>)}{field('How long?',<select className='input' value={value.duration} onChange={e=>setValue({...value,duration:e.target.value})}>{durations.map(v=><option key={v} value={v}>{v} minutes</option>)}</select>)}{field('Usually due again after',<select className='input' value={value.rebookDays} onChange={e=>setValue({...value,rebookDays:e.target.value})}>{rebookOptions.map(v=><option key={v} value={v}>{v} days</option>)}</select>)}<div className='md:col-span-2'>{field('Short description',<textarea className='input min-h-20' value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/>)}</div><div className='flex flex-wrap gap-2 md:col-span-2'><button className='pill dark justify-center' disabled={busy||!value.name||value.price===''}>{busy&&<Loader2 size={15} className='animate-spin'/>}{submitLabel}</button>{submitLabel==='Save changes'&&<button type='button' className='pill light' onClick={()=>setEditingId('')} disabled={busy}>Cancel</button>}</div></form>;
  return <div className='min-w-0'><div className='flex min-w-0 flex-col justify-between gap-4 md:flex-row md:items-end'><div className='min-w-0'><p className='eyebrow plain'>Services</p><h1 className='mt-2 font-serif text-4xl md:text-5xl'>What can clients book?</h1><p className='mt-3 max-w-2xl text-sm leading-6 text-stone-500'>Keep prices, names and timing accurate. Changes update bookings, your storefront and Growth without rewriting past appointment history.</p></div><button className='pill dark' onClick={()=>{setEditingId('');setAdding(!adding)}}><Plus size={15}/>{adding?'Close':'Add service'}</button></div>{adding&&serviceForm(form,setForm,add,'Add service')}{editingId&&serviceForm(editForm,setEditForm,saveEdit,'Save changes')}{services.length===0&&<div className='mt-6 rounded-[26px] border border-dashed border-stone-300 bg-white p-7 text-center'><h2 className='font-serif text-2xl'>No bookable services yet.</h2><p className='mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500'>Your business stays saved, but it will not appear in Discover until you add a service clients can book.</p><button className='pill dark mt-5' onClick={()=>setAdding(true)}><Plus size={15}/>Add a service</button></div>}<div className='mt-6 grid gap-3 sm:grid-cols-2'>{services.map(s=><article key={s.id} className={`rounded-[24px] border bg-white p-5 transition ${editingId===s.id?'border-stone-950 shadow-[0_16px_42px_rgba(30,24,27,.08)]':'border-stone-200'}`}><div className='flex items-start justify-between gap-4'><div className='min-w-0'><h2 className='font-serif text-2xl'>{s.name}</h2><p className='mt-1 text-sm text-stone-500'>{s.duration} min · usually due again after {s.rebookDays} days</p></div><b className='shrink-0'>{money(s.price)}</b></div>{s.description&&<p className='mt-4 text-sm leading-6 text-stone-500'>{s.description}</p>}<div className='mt-5 flex items-center gap-2 border-t border-stone-100 pt-4'><button type='button' className='mini-btn' onClick={()=>beginEdit(s)} disabled={busy}>Edit service</button><button type='button' className='mini-btn text-red-700' onClick={()=>remove(s)} disabled={busy}><Trash2 size={13}/>Delete</button></div>{services.length===1&&<p className='mt-3 text-[11px] leading-4 text-stone-400'>Deleting your last service temporarily removes the business from Discover until another service is added.</p>}</article>)}</div>{msg&&<p className='mt-4 rounded-2xl bg-white p-4 text-sm'>{msg}</p>}</div>
}
